apps/user_panel/urls.py
from django.urls import path
from .views import account, ticket, wallet

urlpatterns = [
    # dashboard
    path('', account.UserDashboardPage.as_view(), name='user_dashboard_page'),
    # account
    path('change-pass/', account.ChangePasswordPage.as_view(), name='change_pass_page'),
    path('change-info/', account.ChangeUserInfoPage.as_view(), name='change_user_info_page'),
    # ticket
    path('tickets/', ticket.TicketsView.as_view(), name='tickets_page'),
    path('tickets/add-ticket', ticket.AddNewTicketPage.as_view(), name='add_new_ticket_page'),
    path('tickets/<int:ticket_id>', ticket.TicketDetailPage.as_view(), name='ticket_detail_page'),
    # wallet
    path('my-wallet/', wallet.UserWalletListView.as_view(), name='user_wallets_page'),
    path('charge-wallet/', wallet.ChargeWalletView.as_view(), name='user_charge_wallet_page'),
]

myacademy_core/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.site.urls')),
    path('user/', include('apps.user_panel.urls')),
    path('admin/', include('apps.admin_panel.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('translator/', include('rosetta.urls')),
    *urlpatterns,
    prefix_default_language=False
)

apps/admin_panel/models/ticket_models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils.translation import gettext_lazy as _


# region ticket

class TicketManager(models.Manager):
    def get_user_tickets(self, user_id):
        return self.get_queryset().filter(owner_id=user_id)

    def get_ticket_for_show(self, ticket_id, user_id):
        return self.get_queryset().filter(id=ticket_id, owner_id=user_id) \
            .prefetch_related('ticketmessage_set', 'ticketmessage_set__sender').first()

    def is_ticket_for_user(self, ticket_id, user_id) -> bool:
        return self.get_queryset().filter(id=ticket_id, owner_id=user_id).exists()

    def get_user_tickets_count(self, user_id):
        return self.get_queryset().filter(owner_id=user_id).count()


class Ticket(models.Model):
    class TicketSection(models.TextChoices):
        SUPPORT = 'SUPPORT', _('Support')
        TECHNICAL = 'Technical', _('Technical')
        FINANCIAL = 'Financial', _('Financial')

    class TicketState(models.TextChoices):
        ANSWERED = 'Answered', _('Answered')
        NOT_ANSWERED = 'NotAnswered', _('Not answered')
        CLOSED = 'Closed', _('Closed')
        UNDER_PROGRESS = 'UnderProgress', _('Under progress')

    class TicketPriority(models.TextChoices):
        LOW = 'Low', _('Low')
        MEDIUM = 'Medium', _('Medium')
        HIGH = 'High', _('High')

    title = models.CharField(max_length=300, verbose_name=_('Title'))
    ticket_section = models.CharField(max_length=300, choices=TicketSection.choices, default=TicketSection.TECHNICAL, verbose_name=_('Ticket section'))
    ticket_state = models.CharField(max_length=300, choices=TicketState.choices, default=TicketState.NOT_ANSWERED, verbose_name=_('Ticket state'))
    ticket_priority = models.CharField(max_length=300, choices=TicketPriority.choices, default=TicketPriority.MEDIUM, verbose_name=_('Priority'))
    owner = models.ForeignKey(to='User', on_delete=models.CASCADE, verbose_name=_('Owner'))
    create_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Create date'))
    is_delete = models.BooleanField(verbose_name=_('Deleted or not'))

    objects = TicketManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Ticket')
        verbose_name_plural = _('Tickets')


# endregion

# region ticket message

class TicketMessageManager(models.Manager):
    def get_ticket_messages_for_show_in_user_panel(self, ticket_id):
        return self.get_queryset().filter(ticket_id=ticket_id, is_delete=False).order_by('-create_date')


class TicketMessage(models.Model):
    sender = models.ForeignKey(to='User', on_delete=models.CASCADE, verbose_name=_('Sender'))
    ticket = models.ForeignKey(to='Ticket', on_delete=models.CASCADE, verbose_name=_('Ticket'))
    create_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Create date'))
    text = RichTextField(verbose_name=_('Text'))
    is_delete = models.BooleanField(verbose_name=_('Deleted or not'))

    objects = TicketMessageManager()

    def __str__(self):
        return f'{self.sender.email} - {self.ticket.title}'

    class Meta:
        verbose_name = _('Ticket message')
        verbose_name_plural = _('Ticket messages')

# endregion

apps/user_panel/forms/account.py
from django import forms
from django.core import validators
from django.utils.translation import gettext_lazy as _


# region change password


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'
        }),
        label=_('Current password'),
        validators=[
            validators.MaxLengthValidator(150, _('This field can not have more than 150 characters'))
        ]
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'
        }),
        label=_('Password'),
        validators=[
            validators.MaxLengthValidator(150, _('This field can not have more than 150 characters'))
        ]
    )

    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control'
        }),
        label=_('Confirm password'),
        validators=[
            validators.MaxLengthValidator(150, _('This field can not have more than 150 characters'))
        ]
    )


# endregion

# region change user info

class ChangeUserInfoForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        }),
        label=_('First name'),
        validators=[
            validators.MaxLengthValidator(150, _('This field can not have more than 150 characters'))
        ]
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        }),
        label=_('Last name'),
        validators=[
            validators.MaxLengthValidator(150, _('This field can not have more than 150 characters'))
        ]
    )


# endregion

apps/user_panel/forms/wallet.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ChargeWalletForm(forms.Form):
    price = forms.IntegerField(
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'autocomplete': 'off',
            'placeholder': _('Toman')
        }),
        label=_('Price'),
    )

apps/user_panel/views/account.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views import View
from apps.admin_panel.models import User, Ticket, UserWallet
from apps.user_panel.forms.account import ChangePasswordForm, ChangeUserInfoForm


# region dashboard

@method_decorator(login_required, name='dispatch')
class UserDashboardPage(View):
    def get(self, request: HttpRequest):
        context = {
            'tickets_count': Ticket.objects.get_user_tickets_count(request.user.id),
            'paid_transactions_count': UserWallet.objects.get_user_paid_transactions_count(request.user.id)
        }
        return render(request, 'user_panel/account/index.html', context)


# endregion

# region change password

@method_decorator(login_required, name='dispatch')
class ChangePasswordPage(View):
    def get(self, request: HttpRequest):
        change_pass_form = ChangePasswordForm()
        return render(request, 'user_panel/account/change_password.html', {
            'form': change_pass_form
        })

    def post(self, request: HttpRequest):
        change_pass_form = ChangePasswordForm(request.POST)
        if change_pass_form.is_valid():
            user: User = User.objects.get_user_by_id(request.user.id)
            if user.check_password(change_pass_form.cleaned_data.get('current_password')):
                user.set_password(change_pass_form.cleaned_data.get('password'))
                user.save()
                logout(request)
                messages.add_message(request, messages.SUCCESS, _('Your password has been successfully edited'))
                return redirect(reverse('login_page'))
            else:
                messages.add_message(request, messages.ERROR, _('Your current password is incorrect'))
        return render(request, 'user_panel/account/change_password.html', {
            'form': change_pass_form
        })


# endregion

# region change user information

@method_decorator(login_required, name='dispatch')
class ChangeUserInfoPage(View):
    def get(self, request: HttpRequest):
        user: User = User.objects.get_user_by_id(request.user.id)
        change_info_form = ChangeUserInfoForm(initial={
            'first_name': user.first_name,
            'last_name': user.last_name
        })
        return render(request, 'user_panel/account/change_user_info.html', {'form': change_info_form})

    def post(self, request: HttpRequest):
        change_info_form = ChangeUserInfoForm(request.POST)
        if change_info_form.is_valid():
            user: User = User.objects.get_user_by_id(request.user.id)
            user.first_name = change_info_form.cleaned_data.get('first_name')
            user.last_name = change_info_form.cleaned_data.get('last_name')
            user.save()
            messages.add_message(request, messages.SUCCESS, _('Your information has been successfully edited'))
        else:
            change_info_form.add_error('first_name', _('An error occurred'))
        return render(request, 'user_panel/account/change_user_info.html', {'form': change_info_form})

# endregion

apps/user_panel/views/components.py
from django.http import HttpRequest
from django.shortcuts import render
from apps.admin_panel.models import User


# region user side bar


def user_side_bar_component(request: HttpRequest):
    user: User = User.objects.get_user_for_side_bar(request.user.id)
    return render(request, 'user_panel/components/user_side_bar.html', {
        'user': user
    })

# endregion

apps/user_panel/views/ticket.py
import datetime
from django.contrib import messages
from django.http import HttpRequest, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic.list import ListView
from apps.admin_panel.models import Ticket, TicketMessage
from django.utils.translation import gettext_lazy as _
from apps.user_panel.forms.tickets import AddTicketMessageForm, AddNewTicketForm


# region user tickets

@method_decorator(login_required, name='dispatch')
class TicketsView(ListView):
    template_name = 'user_panel/tickets/all_tickets.html'
    model = Ticket
    paginate_by = 6

    def get_queryset(self):
        request: HttpRequest = self.request
        query = Ticket.objects.filter(owner_id=request.user.id, is_delete=False).order_by('-create_date')

        return query


# endregion

# region ticket detail

@method_decorator(login_required, name='dispatch')
class TicketDetailPage(View):
    def get(self, request: HttpRequest, ticket_id: int):
        ticket: Ticket = Ticket.objects.get_ticket_for_show(ticket_id, request.user.id)
        if ticket is None:
            raise Http404(_('Information not found'))
        ticket_messages = TicketMessage.objects.get_ticket_messages_for_show_in_user_panel(ticket.id)
        add_ticket_message_form = AddTicketMessageForm()
        return render(request, 'user_panel/tickets/ticket_detail.html', {
            'ticket': ticket,
            'ticket_messages': ticket_messages,
            'form': add_ticket_message_form
        })

    def post(self, request: HttpRequest, ticket_id: int):
        add_message_form = AddTicketMessageForm(request.POST)
        if add_message_form.is_valid():
            ticket = Ticket.objects.get_ticket_for_show(ticket_id, request.user.id)
            if ticket is not None:
                ticket_message = TicketMessage(
                    ticket_id=ticket_id,
                    sender_id=request.user.id,
                    text=add_message_form.cleaned_data.get('text'),
                    is_delete=False
                )
                ticket_message.save()
                # update ticket itself
                ticket.ticket_state = Ticket.TicketState.UNDER_PROGRESS
                ticket.save()
                messages.add_message(request, messages.SUCCESS, _('Your message has been send successfully'))
            else:
                raise Http404(_('Information not found'))
        else:
            messages.add_message(request, messages.ERROR, _('Please enter message text'))

        return redirect(reverse('ticket_detail_page', kwargs={'ticket_id': ticket_id}))


# endregion

# region add new ticket

class AddNewTicketPage(View):
    def get(self, request: HttpRequest):
        ticket_form = AddNewTicketForm()
        return render(request, 'user_panel/tickets/add_ticket.html', {'form': ticket_form})

    def post(self, request: HttpRequest):
        ticket_form = AddNewTicketForm(request.POST)
        if ticket_form.is_valid():
            new_ticket = Ticket(
                owner_id=request.user.id,
                create_date=datetime.datetime.now(),
                ticket_state=Ticket.TicketState.UNDER_PROGRESS,
                is_delete=False,
                ticket_priority=ticket_form.cleaned_data.get('priority'),
                ticket_section=ticket_form.cleaned_data.get('section'),
                title=ticket_form.cleaned_data.get('title')
            )
            new_ticket.save()
            new_message = TicketMessage(
                ticket_id=new_ticket.id,
                is_delete=False,
                create_date=datetime.datetime.now(),
                sender_id=request.user.id,
                text=ticket_form.cleaned_data.get('text')
            )
            new_message.save()
            messages.add_message(request, messages.SUCCESS, _('Your ticket submitted successfully'))
            return redirect(reverse('tickets_page'))
        return render(request, 'user_panel/tickets/add_ticket.html', {'form': ticket_form})

# endregion

apps/user_panel/views/wallet.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, Page
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from apps.admin_panel.models import UserWallet
from django.utils.translation import get_language
from apps.user_panel.forms.wallet import ChargeWalletForm
from django.utils.translation import gettext_lazy as _
from utilities.web.http import get_client_ip


# region user wallets list

@method_decorator(login_required, name='dispatch')
class UserWalletListView(View):
    def get(self, request: HttpRequest):
        query, filter_items = UserWallet.objects.filter_wallets(
            user_id=request.user.id,
            start_date=request.GET.get('start_date') or '',
            end_date=request.GET.get('end_date') or '',
            is_paid_check_list=[True]
        )

        paginator = Paginator(query, 10)
        page_obj: Page = paginator.get_page(request.GET.get('page'))
        context = {
            'filter_items': filter_items,
            'paginator': paginator,
            'page_obj': page_obj,
            'current_language': get_language()
        }
        return render(request, 'user_panel/wallets/user_wallets.html', context)


# endregion

# region charge wallet

@method_decorator(login_required, name='dispatch')
class ChargeWalletView(View):
    def get(self, request: HttpRequest):
        charge_form = ChargeWalletForm()
        context = {
            'form': charge_form
        }
        return render(request, 'user_panel/wallets/charge_wallet.html', context)

    def post(self, request: HttpRequest):
        charge_form = ChargeWalletForm(request.POST)
        if charge_form.is_valid():
            UserWallet.objects.charge_user_wallet(request.user.id, charge_form.cleaned_data.get('price'), get_client_ip(request))
            messages.add_message(request, messages.SUCCESS, _('Your wallet has been charged'))
            # todo: send user to bank
            return redirect(reverse('user_wallets_page'))
        else:
            messages.add_message(request, messages.ERROR, _('An error occurred'))

        context = {
            'form': charge_form
        }
        return render(request, 'user_panel/wallets/charge_wallet.html', context)

# endregion

apps/user_panel/templates/user_panel/tickets/add_ticket.html
{% extends 'shared/user_layout.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Add new ticket' %}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'tickets_page' %}">{% trans 'Tickets' %}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">{% trans 'Add new ticket' %}</li>
{% endblock %}

{% block footer_references %}
    {% include 'shared/ckeditor_scripts.html' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="dashboard_container">
                <div class="dashboard_container_header">
                    <div class="dashboard_fl_1">
                        <h4>{% trans 'Add new ticket' %}</h4>
                    </div>
                </div>
                <div class="dashboard_container_body p-4">
                    <form action="{% url 'add_new_ticket_page' %}" method="post">
                        {% csrf_token %}
                        <div class="submit-section">
                            <div class="form-row">
                                {% for field in form %}
                                    <div class="form-group col-md-12">
                                        {{ field.label_tag }}
                                        {{ field }}
                                        {% for error in field.errors %}
                                            <p class="text-danger">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endfor %}

                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-success">{% trans 'Submit' %}</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

apps/user_panel/templates/user_panel/tickets/all_tickets.html
{% extends 'shared/user_layout.html' %}
{% load i18n %}
{% load jalali_date_filter %}
{% load ticket_list_style %}

{% block title %}
    {% trans 'Tickets' %}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'tickets_page' %}">{% trans 'Tickets' %}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">{% trans 'User tickets' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <form action="{% url 'tickets_page' %}" method="get" id="filter-form">
            <input type="hidden" name="page" value="{{ page_obj.number }}" id="page-number">
        </form>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="dashboard_container">
                <div class="dashboard_container_header">
                    <div class="dashboard_fl_1">
                        <h4>{% trans 'All tickets list' %}</h4>
                    </div>
                </div>
                <div class="dashboard_container_body">
                    {% if ticket_list %}
                        <div class="table-responsive">
                            <table class="table">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">{% trans 'Code' %}</th>
                                    <th scope="col">{% trans 'Title' %}</th>
                                    <th scope="col">{% trans 'Create data' %}</th>
                                    <th scope="col">{% trans 'Status' %}</th>
                                    <th scope="col">{% trans 'Operations' %}</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for ticket in object_list %}
                                    <tr>
                                        <th scope="row">{{ ticket.id }}</th>
                                        <td>{{ ticket.title }}</td>
                                        <td>{{ ticket.create_date|show_jalali_date }}</td>
                                        <td>
                                            <span class="payment_status {{ ticket.ticket_state|show_ticket_state }}">
                                                {{ ticket.get_ticket_state_display }}
                                            </span>
                                        </td>
                                        <td>
                                            <div class="dash_action_link">
                                                <a href="{% url 'ticket_detail_page' ticket_id=ticket.id %}"
                                                   class="view">{% trans 'Show Detail' %}</a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                            {% include 'user_panel/shared/user_paging_partial.html' with paginator=paginator page_obj=page_obj %}
                        </div>
                    {% else %}
                        {% include 'user_panel/shared/user_not_fount_partial.html' %}
                    {% endif %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

apps/user_panel/templates/user_panel/tickets/ticket_detail.html
{% extends 'shared/user_layout.html' %}
{% load i18n %}
{% load jalali_date_filter %}

{% block title %}
    {% trans 'Ticket detail' %} | {{ ticket.title }}
{% endblock %}

{% block header_references %}
    {% include 'shared/ckeditor_scripts.html' %}
{% endblock %}


{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'tickets_page' %}">{% trans 'Tickets' %}</a>
    </li>
    <li class="breadcrumb-item" aria-current="page">{% trans 'Ticket detail' %}</li>
    <li class="breadcrumb-item active" aria-current="page">{{ ticket.title }}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="dashboard_container">
                <div class="dashboard_container_header">
                    <div class="dashboard_fl_1">
                        <h4>{{ ticket.title }}</h4>
                    </div>
                </div>
                <div class="dashboard_container_body p-4">
                    <div class="revies-comments-wrap">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ form.text }}
                            <button class="btn btn-success">{% trans 'Send' %}</button>
                        </form>
                    </div>
                    <div class="reviews-comments-wrap">
                        {% for ticket_message in ticket_messages %}
                            <div class="reviews-comments-item">
                                <div class="review-comments-avatar">
                                    {% if ticket_message.sender_id != ticket.owner_id %}
                                        <img src="{{ ticket.owner.get_user_default_avatar }}" class="img-fluid" alt="">
                                    {% else %}
                                        <img src="{{ ticket.owner.get_user_avatar }}" class="img-fluid" alt="">
                                    {% endif %}
                                </div>
                                <div class="reviews-comments-item-text">
                                    <h4>
                                        {% if ticket.owner_id != ticket_message.sender_id %}
                                            <a>{% trans 'Support' %}</a>
                                        {% else %}
                                            <a>{{ ticket_message.sender }}</a>
                                        {% endif %}
                                        <span class="reviews-comments-item-date">
                                        <i class="ti-calendar theme-cl"></i>
                                            {{ ticket_message.create_date|show_jalali_date }} - {{ ticket_message.create_date|time }}
                                        </span>
                                    </h4>
                                    <div class="clearfix"></div>
                                    {{ ticket_message.text|safe }}
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}