apps/user_panel/urls.py
from django.urls import path
from .views import account, ticket, wallet

urlpatterns = [
    # dashboard
    path('', account.UserDashboardPage.as_view(), name='user_dashboard_page'),
    # account
    path('change-pass/', account.ChangePasswordPage.as_view(), name='change_pass_page'),
    path('change-info/', account.ChangeUserInfoPage.as_view(), name='change_user_info_page'),
    # ticket
    path('tickets/', ticket.TicketsView.as_view(), name='tickets_page'),
    path('tickets/add-ticket', ticket.AddNewTicketPage.as_view(), name='add_new_ticket_page'),
    path('tickets/<int:ticket_id>', ticket.TicketDetailPage.as_view(), name='ticket_detail_page'),
    # wallet
    path('my-wallet/', wallet.UserWalletListView.as_view(), name='user_wallets_page'),
    path('charge-wallet/', wallet.ChargeWalletView.as_view(), name='user_charge_wallet_page'),
]

myacademy_core/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.site.urls')),
    path('user/', include('apps.user_panel.urls')),
    path('admin/', include('apps.admin_panel.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('translator/', include('rosetta.urls')),
    *urlpatterns,
    prefix_default_language=False
)

apps/admin_panel/models/wallet_models.py
from django.db import models
from django.utils.translation import get_language
from django.utils.translation import gettext_lazy as _
from utilities.convertors import date_convertor


# region user wallet

class UserWalletManager(models.Manager):
    def charge_user_wallet(self, user_id, price, user_ip):
        wallet = UserWallet(user_id=user_id, price=price, user_ip=user_ip, transaction_for=UserWallet.TransactionFor.CHARGE, transaction_type=UserWallet.TransactionType.DEPOSIT, transaction_way=UserWallet.TransactionWay.ONLINE)
        wallet.save()

    def get_user_paid_transactions_count(self, user_id):
        return self.get_queryset().filter(is_paid=True, user_id=user_id).count()

    def filter_wallets(self, **kwargs):
        query = self.get_queryset()
        transaction_for_list = kwargs.get('transaction_for_list')
        transaction_way_list = kwargs.get('transaction_way_list')
        transaction_type_list = kwargs.get('transaction_type_list')
        user_id = kwargs.get('user_id')
        start_date = kwargs.get('start_date')
        end_date = kwargs.get('end_date')
        tracking_code = kwargs.get('tracking_code')
        is_paid_check_list = kwargs.get('is_paid_check_list')
        lang = get_language()
        if lang == 'fa':
            start_date = date_convertor.convert_shamsi_to_miladi(start_date)
            end_date = date_convertor.convert_shamsi_to_miladi(end_date)

        if transaction_for_list is not None:
            query = query.filter(transaction_way__in=transaction_way_list)

        if transaction_type_list is not None:
            query = query.filter(transaction_type__in=transaction_type_list)

        if transaction_way_list is not None:
            query = query.filter(transaction_way__in=transaction_way_list)

        if user_id is not None:
            query = query.filter(user_id=user_id)

        if start_date is not None and start_date is not '':
            query = query.filter(payment_date__gte=start_date)

        if end_date is not None and end_date is not '':
            query = query.filter(payment_date__lte=end_date)

        if tracking_code is not None:
            query = query.filter(tracking_code__icontains=tracking_code)

        if is_paid_check_list is not None:
            query = query.filter(is_paid__in=is_paid_check_list)

        return query.distinct(), kwargs


class UserWallet(models.Model):
    class TransactionType(models.TextChoices):
        DEPOSIT = 'DEPOSIT', _('Deposit')
        WITHDRAWAL = 'WITHDRAWAL', _('Withdrawal')

    class TransactionWay(models.TextChoices):
        ONLINE = 'ONLINE', _('Online')
        CASH = 'CASH', _('CASH')
        CHARGE_BY_ADMIN = 'CHARGE_BY_ADMIN', _('Charge by admin')
        CARD_TO_CARD = 'CARD_TO_CARD', _('Card to card')

    class TransactionFor(models.TextChoices):
        DISCOUNT = 'DISCOUNT', _('Discount')
        BUY_COURSE = 'BUY_COURSE', _('Buy course')
        CHARGE = 'CHARGE', _('Charge wallet')
        CHECK_OUT = 'CHECK_OUT', _('Checkout')
        REQUEST_CERTIFICATE = 'REQUEST_CERTIFICATE', _('Request certificate')
        REFUND = 'REFUND', _('Refund')
        CONSULT = 'CONSULT', _('Consult')
        OTHER = 'OTHER', _('Other')

    user = models.ForeignKey('User', on_delete=models.CASCADE, verbose_name=_('User'))
    price = models.IntegerField(default=0, verbose_name=_('Price'))
    transaction_type = models.CharField(choices=TransactionType.choices, max_length=200, verbose_name=_('Transaction type'))
    transaction_way = models.CharField(choices=TransactionWay.choices, max_length=200, verbose_name=_('Transaction way'))
    transaction_for = models.CharField(choices=TransactionFor.choices, max_length=200, verbose_name=_('Transaction for'))
    is_paid = models.BooleanField(default=False, verbose_name=_('Is paid'))
    create_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Create date'))
    payment_date = models.DateTimeField(null=True, blank=True, verbose_name=_('Payment date'))
    description = models.TextField(null=True, blank=True, verbose_name=_('Description'))
    user_ip = models.CharField(max_length=50, null=True, blank=True, verbose_name=_('User IP'))
    authority = models.CharField(max_length=50, null=True, blank=True, verbose_name=_('Authority'))
    tracking_code = models.CharField(max_length=200, null=True, blank=True, verbose_name=_('Tracking code'))

    objects = UserWalletManager()

    def __str__(self):
        return f'{self.user} / {self.price}'

    class Meta:
        verbose_name = _('User wallet')
        verbose_name_plural = _('User wallets')

# endregion

apps/user_panel/forms/wallet.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ChargeWalletForm(forms.Form):
    price = forms.IntegerField(
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'autocomplete': 'off',
            'placeholder': _('Toman')
        }),
        label=_('Price'),
    )

apps/user_panel/views/account.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views import View
from apps.admin_panel.models import User, Ticket, UserWallet
from apps.user_panel.forms.account import ChangePasswordForm, ChangeUserInfoForm


# region dashboard

@method_decorator(login_required, name='dispatch')
class UserDashboardPage(View):
    def get(self, request: HttpRequest):
        context = {
            'tickets_count': Ticket.objects.get_user_tickets_count(request.user.id),
            'paid_transactions_count': UserWallet.objects.get_user_paid_transactions_count(request.user.id)
        }
        return render(request, 'user_panel/account/index.html', context)


# endregion

# region change password

@method_decorator(login_required, name='dispatch')
class ChangePasswordPage(View):
    def get(self, request: HttpRequest):
        change_pass_form = ChangePasswordForm()
        return render(request, 'user_panel/account/change_password.html', {
            'form': change_pass_form
        })

    def post(self, request: HttpRequest):
        change_pass_form = ChangePasswordForm(request.POST)
        if change_pass_form.is_valid():
            user: User = User.objects.get_user_by_id(request.user.id)
            if user.check_password(change_pass_form.cleaned_data.get('current_password')):
                user.set_password(change_pass_form.cleaned_data.get('password'))
                user.save()
                logout(request)
                messages.add_message(request, messages.SUCCESS, _('Your password has been successfully edited'))
                return redirect(reverse('login_page'))
            else:
                messages.add_message(request, messages.ERROR, _('Your current password is incorrect'))
        return render(request, 'user_panel/account/change_password.html', {
            'form': change_pass_form
        })


# endregion

# region change user information

@method_decorator(login_required, name='dispatch')
class ChangeUserInfoPage(View):
    def get(self, request: HttpRequest):
        user: User = User.objects.get_user_by_id(request.user.id)
        change_info_form = ChangeUserInfoForm(initial={
            'first_name': user.first_name,
            'last_name': user.last_name
        })
        return render(request, 'user_panel/account/change_user_info.html', {'form': change_info_form})

    def post(self, request: HttpRequest):
        change_info_form = ChangeUserInfoForm(request.POST)
        if change_info_form.is_valid():
            user: User = User.objects.get_user_by_id(request.user.id)
            user.first_name = change_info_form.cleaned_data.get('first_name')
            user.last_name = change_info_form.cleaned_data.get('last_name')
            user.save()
            messages.add_message(request, messages.SUCCESS, _('Your information has been successfully edited'))
        else:
            change_info_form.add_error('first_name', _('An error occurred'))
        return render(request, 'user_panel/account/change_user_info.html', {'form': change_info_form})

# endregion

apps/user_panel/views/components.py
from django.http import HttpRequest
from django.shortcuts import render
from apps.admin_panel.models import User


# region user side bar


def user_side_bar_component(request: HttpRequest):
    user: User = User.objects.get_user_for_side_bar(request.user.id)
    return render(request, 'user_panel/components/user_side_bar.html', {
        'user': user
    })

# endregion

apps/user_panel/views/ticket.py
import datetime
from django.contrib import messages
from django.http import HttpRequest, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic.list import ListView
from apps.admin_panel.models import Ticket, TicketMessage
from django.utils.translation import gettext_lazy as _
from apps.user_panel.forms.tickets import AddTicketMessageForm, AddNewTicketForm


# region user tickets

@method_decorator(login_required, name='dispatch')
class TicketsView(ListView):
    template_name = 'user_panel/tickets/all_tickets.html'
    model = Ticket
    paginate_by = 6

    def get_queryset(self):
        request: HttpRequest = self.request
        query = Ticket.objects.filter(owner_id=request.user.id, is_delete=False).order_by('-create_date')

        return query


# endregion

# region ticket detail

@method_decorator(login_required, name='dispatch')
class TicketDetailPage(View):
    def get(self, request: HttpRequest, ticket_id: int):
        ticket: Ticket = Ticket.objects.get_ticket_for_show(ticket_id, request.user.id)
        if ticket is None:
            raise Http404(_('Information not found'))
        ticket_messages = TicketMessage.objects.get_ticket_messages_for_show_in_user_panel(ticket.id)
        add_ticket_message_form = AddTicketMessageForm()
        return render(request, 'user_panel/tickets/ticket_detail.html', {
            'ticket': ticket,
            'ticket_messages': ticket_messages,
            'form': add_ticket_message_form
        })

    def post(self, request: HttpRequest, ticket_id: int):
        add_message_form = AddTicketMessageForm(request.POST)
        if add_message_form.is_valid():
            ticket = Ticket.objects.get_ticket_for_show(ticket_id, request.user.id)
            if ticket is not None:
                ticket_message = TicketMessage(
                    ticket_id=ticket_id,
                    sender_id=request.user.id,
                    text=add_message_form.cleaned_data.get('text'),
                    is_delete=False
                )
                ticket_message.save()
                # update ticket itself
                ticket.ticket_state = Ticket.TicketState.UNDER_PROGRESS
                ticket.save()
                messages.add_message(request, messages.SUCCESS, _('Your message has been send successfully'))
            else:
                raise Http404(_('Information not found'))
        else:
            messages.add_message(request, messages.ERROR, _('Please enter message text'))

        return redirect(reverse('ticket_detail_page', kwargs={'ticket_id': ticket_id}))


# endregion

# region add new ticket

class AddNewTicketPage(View):
    def get(self, request: HttpRequest):
        ticket_form = AddNewTicketForm()
        return render(request, 'user_panel/tickets/add_ticket.html', {'form': ticket_form})

    def post(self, request: HttpRequest):
        ticket_form = AddNewTicketForm(request.POST)
        if ticket_form.is_valid():
            new_ticket = Ticket(
                owner_id=request.user.id,
                create_date=datetime.datetime.now(),
                ticket_state=Ticket.TicketState.UNDER_PROGRESS,
                is_delete=False,
                ticket_priority=ticket_form.cleaned_data.get('priority'),
                ticket_section=ticket_form.cleaned_data.get('section'),
                title=ticket_form.cleaned_data.get('title')
            )
            new_ticket.save()
            new_message = TicketMessage(
                ticket_id=new_ticket.id,
                is_delete=False,
                create_date=datetime.datetime.now(),
                sender_id=request.user.id,
                text=ticket_form.cleaned_data.get('text')
            )
            new_message.save()
            messages.add_message(request, messages.SUCCESS, _('Your ticket submitted successfully'))
            return redirect(reverse('tickets_page'))
        return render(request, 'user_panel/tickets/add_ticket.html', {'form': ticket_form})

# endregion

apps/user_panel/views/wallet.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, Page
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from apps.admin_panel.models import UserWallet
from django.utils.translation import get_language
from apps.user_panel.forms.wallet import ChargeWalletForm
from django.utils.translation import gettext_lazy as _
from utilities.web.http import get_client_ip


# region user wallets list

@method_decorator(login_required, name='dispatch')
class UserWalletListView(View):
    def get(self, request: HttpRequest):
        query, filter_items = UserWallet.objects.filter_wallets(
            user_id=request.user.id,
            start_date=request.GET.get('start_date') or '',
            end_date=request.GET.get('end_date') or '',
            is_paid_check_list=[True]
        )

        paginator = Paginator(query, 10)
        page_obj: Page = paginator.get_page(request.GET.get('page'))
        context = {
            'filter_items': filter_items,
            'paginator': paginator,
            'page_obj': page_obj,
            'current_language': get_language()
        }
        return render(request, 'user_panel/wallets/user_wallets.html', context)


# endregion

# region charge wallet

@method_decorator(login_required, name='dispatch')
class ChargeWalletView(View):
    def get(self, request: HttpRequest):
        charge_form = ChargeWalletForm()
        context = {
            'form': charge_form
        }
        return render(request, 'user_panel/wallets/charge_wallet.html', context)

    def post(self, request: HttpRequest):
        charge_form = ChargeWalletForm(request.POST)
        if charge_form.is_valid():
            UserWallet.objects.charge_user_wallet(request.user.id, charge_form.cleaned_data.get('price'), get_client_ip(request))
            messages.add_message(request, messages.SUCCESS, _('Your wallet has been charged'))
            # todo: send user to bank
            return redirect(reverse('user_wallets_page'))
        else:
            messages.add_message(request, messages.ERROR, _('An error occurred'))

        context = {
            'form': charge_form
        }
        return render(request, 'user_panel/wallets/charge_wallet.html', context)

# endregion

apps/user_panel/templates/user_panel/wallets/charge_wallet.html
{% extends 'shared/user_layout.html' %}
{% load i18n %}
{% load currency_filter %}

{% block title %}
    {% trans 'Charge wallet' %}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'user_wallets_page' %}">{% trans 'Wallet' %}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">{% trans 'Charge wallet' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="dashboard_container">
                <div class="dashboard_container_header">
                    <div class="dashboard_fl_1">
                        <h4>{% trans 'Charge wallet' %}</h4>
                    </div>
                </div>
                <div class="dashboard_container_body p-4">
                    <form action="{% url 'user_charge_wallet_page' %}" method="post">
                        {% csrf_token %}
                        <div class="submit-section">
                            <div class="form-row">
                                {% for field in form %}
                                    <div class="form-group col-md-12">
                                        {{ field.label_tag }}
                                                {{ field }}
                                        {% for error in field.errors %}
                                            <p class="text-danger">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endfor %}

                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-success">{% trans 'Charge wallet' %}</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

apps/user_panel/templates/user_panel/wallets/user_wallets.html
{% extends 'shared/user_layout.html' %}
{% load static %}
{% load currency_filter %}
{% load jalali_date_filter %}
{% load i18n %}

{% block title %}
    {% trans 'My wallet' %}
{% endblock %}

{% block header_references %}
    <link rel="stylesheet" href="{% static 'lib/kamadatepicker/kamadatepicker.css' %}">
{% endblock %}

{% block footer_references %}
    <script src="{% static 'lib/kamadatepicker/kamadatepicker.js' %}"></script>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'user_wallets_page' %}">{% trans 'Wallet' %}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">{% trans 'My wallet transactions' %}</li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="dashboard_container">
                <div class="dashboard_container_header">
                    <div class="dashboard_fl_1">
                        <h4>{% trans 'All transactions list' %}</h4>
                    </div>
                </div>
                <div class="dashboard_container_body pl-3 pr-3 mt-3">
                    <form action="{% url 'user_wallets_page' %}" method="get" id="filter-form">
                        <input type="hidden" name="page" value="{{ page_obj.number }}" id="page-number">
                        <br>
                        {% if current_language == 'fa' %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="start_date">{% trans 'Start date' %}</label>
                                        <input type="text" autocomplete="off" date-picker value="{{ filter_items.start_date }}" name="start_date" id="start_date" placeholder="{% trans 'Start date' %}" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="end_date">{% trans 'End date' %}</label>
                                        <input type="text" autocomplete="off" date-picker value="{{ filter_items.end_date }}" name="end_date" id="end_date" placeholder="{% trans 'End date' %}" class="form-control">
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="start_date">{% trans 'Start date' %}</label>
                                        <input type="date" value="{{ filter_items.start_date }}" name="start_date" id="start_date" placeholder="{% trans 'Start date' %}" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="end_date">{% trans 'End date' %}</label>
                                        <input type="date" value="{{ filter_items.end_date }}" name="end_date" id="end_date" placeholder="{% trans 'End date' %}" class="form-control">
                                    </div>
                                </div>
                            </div>
                        {% endif %}

                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group mt-4">
                                    <button class="btn btn-success btn-block">{% trans 'Search' %}</button>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group mt-4">
                                    <a href="{% url 'user_charge_wallet_page' %}" class="btn btn-dark btn-block">{% trans 'Charge wallet' %}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                    {% if page_obj.object_list %}
                        <div class="table-responsive">
                            <table class="table">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">{% trans 'Price' %}</th>
                                    <th scope="col">{% trans 'Transaction type' %}</th>
                                    <th scope="col">{% trans 'Transaction for' %}</th>
                                    <th scope="col">{% trans 'Payment date' %}</th>
                                    <th scope="col">{% trans 'Tracking code' %}</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for item in page_obj.object_list %}
                                    <tr>
                                        <td>{{ item.price|three_digits_currency }}</td>
                                        <td>{{ item.get_transaction_type_display }}</td>
                                        <td>{{ item.get_transaction_for_display }}</td>
                                        <td>{{ item.payment_date|show_jalali_date }} - {{ item.payment_date|time }}</td>
                                        <td>
                                            {% if item.tracking_code %}
                                                <span>{{ item.tracking_code }}</span>
                                            {% else %}
                                                <span>{% trans 'Not set' %}</span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                            {% include 'user_panel/shared/user_paging_partial.html' with paginator=paginator page_obj=page_obj %}
                        </div>
                    {% endif %}
                </div>

                {% if not page_obj.object_list %}
                    {% include 'user_panel/shared/user_not_fount_partial.html' %}
                {% endif %}

            </div>
        </div>

    </div>
{% endblock %}