apps/site/urls.py
from django.urls import path
from .views import home, account, articles, courses

urlpatterns = [
    # home
    path('', home.home_page, name='home_page'),
    path('contact-us/', home.ContactView.as_view(), name='contact_us_page'),
    path('about-us/', home.about_us_view, name='about_us_page'),
    path('page/<str:url_title>', home.dynamic_page, name='dynamic_page_view'),
    # account
    path('register/', account.RegisterPage.as_view(), name='register_page'),
    path('login/', account.LoginPage.as_view(), name='login_page'),
    path('logout/', account.LogoutPage.as_view(), name='logout_page'),
    path('forgot-pass/', account.ForgotPasswordPage.as_view(), name='forgot_password_page'),
    path('reset-pass/<str:email_active_code>', account.ResetPasswordPage.as_view(), name='reset_password_page'),
    path('activate-account/<email_active_code>', account.ActivateAccountPage.as_view(), name='activate_account_page'),
    # articles
    path('a/<int:article_id>', articles.article_short_link, name='articles_short_link_page'),
    path('articles/', articles.ArticlesPage.as_view(), name='articles_list_page'),
    path('articles/add-comment/<int:article_id>', articles.AddArticleCommentPage.as_view(), name='add_article_comment_page'),
    path('articles/<int:article_id>/<str:article_title>', articles.ArticleDetailPage.as_view(), name='articles_detail_page'),
    # courses
    path('courses/', courses.CoursesListView.as_view(), name='courses_list_page'),
    path('courses/add-course-comment', courses.SubmitCourseCommentView.as_view(), name='add_course_comment'),
    path('courses/<slug:slug>', courses.CourseDetailView.as_view(), name='courses_detail_page'),
]

myacademy_core/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.site.urls')),
    path('user/', include('apps.user_panel.urls')),
    path('admin/', include('apps.admin_panel.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('translator/', include('rosetta.urls')),
    *urlpatterns,
    prefix_default_language=False
)

apps/admin_panel/models/courses_models.py
import os
import datetime
from ckeditor.fields import RichTextField
from django.db import models
from django.db.models import Prefetch, Count, Q, Sum, F
from django.db.models.functions import Cast
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _


# region course category

class CourseCategoryManager(models.Manager):
    def get_all_active_categories_with_sub_categories(self):
        return self.get_queryset().filter(is_active=True, parent_id__isnull=True) \
            .prefetch_related(Prefetch('coursecategory_set', queryset=CourseCategory.objects.filter(is_active=True).annotate(courses_count=Count('course')))) \
            .annotate(courses_count=Count('course'))


class CourseCategory(models.Model):
    title = models.CharField(max_length=200, unique=True, verbose_name=_('Title'))
    url_title = models.CharField(max_length=200, unique=True, verbose_name=_('Url title'))
    icon_name = models.CharField(max_length=200, null=True, blank=True, verbose_name=_('Icon name'))
    image = models.ImageField(upload_to='images/course-category', null=True, blank=True, verbose_name=_('Image'))
    short_description = models.CharField(max_length=1000, verbose_name=_('Short description'))
    description = RichTextField(null=True, blank=True, verbose_name=_('Description'))
    is_active = models.BooleanField(default=True, verbose_name=_('Is active'))
    parent = models.ForeignKey('CourseCategory', on_delete=models.CASCADE, null=True, blank=True, verbose_name=_('Parent'))
    is_delete = models.BooleanField(default=False, verbose_name=_('Is deleted'))

    objects = CourseCategoryManager()

    def __str__(self):
        return f'{self.title} / {self.url_title}'

    class Meta:
        verbose_name = _('Course category')
        verbose_name_plural = _('Course categories')


# endregion

# region course level

class CourseLevelManager(models.Manager):
    def get_all_levels_by_order(self):
        return self.get_queryset().annotate(courses_count=Count('course')).order_by('order')


class CourseLevel(models.Model):
    title = models.CharField(max_length=200, verbose_name=_('Title'))
    url_title = models.CharField(max_length=200, verbose_name=_('Url title'))
    order = models.IntegerField(default=0, verbose_name=_('Order'))

    objects = CourseLevelManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Course level')
        verbose_name_plural = _('Course levels')


# endregion

# region course

class CourseManager(models.Manager):
    def get_course_by_id(self, course_id):
        return self.get_queryset().filter(id=course_id).first()

    def get_all_active_courses_count(self):
        return self.get_queryset().count()

    def get_course_for_show(self, course_slug):
        return self.get_queryset().filter(slug__iexact=course_slug) \
            .prefetch_related('categories', 'courseprerequisite_set', 'course_levels', 'course_features') \
            .annotate(
            sections_count=Count('coursesection', filter=Q(coursesection__publish_date__lte=datetime.datetime.now())),
            total_section_duration=Sum(F('coursesection__duration__hour') * 60 + F('coursesection__duration__minute'))) \
            .first()

    def filter_courses(self, **kwargs):
        query = self.get_queryset().prefetch_related('main_master', 'main_master__user') \
            .annotate(total_section_duration=Sum(F('coursesection__duration__hour') * 60 + F('coursesection__duration__minute'))) \
            .order_by('-id')
        title = kwargs.get('title')
        categories = kwargs.get('categories')
        course_levels = kwargs.get('course_levels')
        course_states = kwargs.get('course_states')
        course_master_user_id = kwargs.get('master_user_id')

        if title is not None:
            query = query.filter(Q(title__icontains=title) | Q(short_description__icontains=title) | Q(description__icontains=title) | Q(coursetag__title__icontains=title))

        if categories:
            query = query.filter(categories__url_title__in=categories)

        if course_levels is not None and len(course_levels):
            query = query.filter(course_levels__url_title__in=course_levels)

        if course_states is not None and len(course_states):
            query = query.filter(course_status__in=course_states)

        if course_master_user_id is not None:
            query = query.filter(Q(main_master_id=course_master_user_id) | Q(other_masters__user_id=course_master_user_id))

        return query.distinct(), kwargs


def course_introduction_upload_path(instance, filepath):
    name, ext = os.path.splitext(os.path.basename(filepath))
    section_name = get_random_string(75)
    return f"files/introductions/{instance.folder_name}/{section_name}{ext}"


class Course(models.Model):
    class CourseHoldState(models.TextChoices):
        PREPARING = 'PREPARING', _('Preparing')
        ON_PERFORMING = 'ON_PERFORMING', _('On performing')
        FINISHED = 'FINISHED', _('Finished')
        HAS_STOPPED = 'HAS_STOPPED', _('Has stopped')

    title = models.CharField(max_length=300, db_index=True, unique=True, verbose_name=_('Title'))
    slug = models.SlugField(max_length=300, unique=True, verbose_name=_('Course slug field'))
    course_status = models.CharField(max_length=300, choices=CourseHoldState.choices, default=CourseHoldState.PREPARING, verbose_name=_('Course hold status'))
    image = models.ImageField(upload_to='images/course', max_length=200, verbose_name=_('Image'))
    price = models.IntegerField(default=0, verbose_name=_('Price'))
    short_description = models.CharField(max_length=500, verbose_name=_('Short description'))
    description = RichTextField(verbose_name=_('Description'))
    main_master = models.ForeignKey('CourseMaster', related_name='master_courses', on_delete=models.CASCADE, verbose_name=_('Course main master'))
    other_masters = models.ManyToManyField('CourseMaster', blank=True, related_name='other_master_courses', verbose_name=_('Course other masters'))
    course_levels = models.ManyToManyField('CourseLevel', verbose_name=_('Course levels'))
    categories = models.ManyToManyField('CourseCategory', verbose_name=_('Categories'))
    visit_count = models.IntegerField(default=0, verbose_name=_('Visit count'))
    create_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Create date'))
    can_send_comment = models.BooleanField(default=True, verbose_name=_('Can send comment'))
    show_comments = models.BooleanField(default=True, verbose_name=_('Show comments'))
    estimate_finish_time = models.CharField(max_length=300, null=True, blank=True, verbose_name=_('Estimated time to complete the course'))
    is_delete = models.BooleanField(default=False, verbose_name=_('Is deleted'))
    folder_name = models.CharField(max_length=500, unique=True, verbose_name=_('Folder name'))
    video = models.FileField(upload_to=course_introduction_upload_path, null=True, blank=True, max_length=200, verbose_name=_('Video'))

    objects = CourseManager()

    def __str__(self):
        return f'{self.title} / {self.main_master.user}'

    class Meta:
        verbose_name = _('Course')
        verbose_name_plural = _('Courses')

    def get_detail_url(self):
        return reverse('courses_detail_page', kwargs={'slug': self.slug})

    def get_course_price_display(self):
        if self.price != 0:
            return '{:,}'.format(self.price) + ' ' + _('Toman')
        else:
            return _('Free')


# endregion

# region course headings

class CourseHeadingManager(models.Manager):
    def get_course_headings_by_course_id(self, course_id):
        return self.get_queryset().order_by('order') \
            .prefetch_related(Prefetch('heading_sections', queryset=CourseSection.objects.filter(publish_date__lte=datetime.datetime.now()))) \
            .filter(course_id=course_id, show_to_user=True)


class CourseHeading(models.Model):
    title = models.CharField(max_length=500, verbose_name=_('Title'))
    order = models.IntegerField(default=0, verbose_name=_('Order'))
    show_to_user = models.BooleanField(verbose_name=_('Show to user'))
    course = models.ForeignKey('Course', on_delete=models.CASCADE, verbose_name=_('Course'))

    objects = CourseHeadingManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Course heading')
        verbose_name_plural = _('Course headings')


# endregion

# region course sections

def course_section_video_upload_path(instance, filepath):
    name, ext = os.path.splitext(os.path.basename(filepath))
    section_name = get_random_string(75)
    return f"files/courses/{instance.course.folder_name}/videos/{section_name}{ext}"


def course_section_file_upload_path(instance, filepath):
    name, ext = os.path.splitext(os.path.basename(filepath))
    section_name = get_random_string(75)
    return f"files/courses/{instance.course.folder_name}/files/{section_name}{ext}"


class CourseSectionManager(models.Manager):
    pass


class CourseSection(models.Model):
    title = models.CharField(max_length=500, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    order = models.IntegerField(default=0, verbose_name=_('Order'))
    duration = models.TimeField(verbose_name=_('Duration'))
    is_free = models.BooleanField(verbose_name=_('Is free'))
    video = models.FileField(upload_to=course_section_video_upload_path, max_length=200, verbose_name=_('Video'))
    file = models.FileField(upload_to=course_section_file_upload_path, max_length=200, verbose_name=_('File'))
    course = models.ForeignKey('Course', on_delete=models.CASCADE, verbose_name=_('Course'))
    course_heading = models.ForeignKey('CourseHeading', related_name='heading_sections', on_delete=models.CASCADE, verbose_name=_('Course heading'))

apps/admin_panel/views/home.py
from django.http import HttpRequest
from django.shortcuts import render


def home_page(request: HttpRequest):
    return render(request, 'admin_panel/home/index_page.html')

apps/site/views/articles.py
import datetime
from django.contrib import messages
from django.http import HttpRequest, Http404
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic.list import ListView
from apps.admin_panel import models as domains
from apps.site.forms.article import AddArticleCommentForm


# region articles list

class ArticlesPage(ListView):
    model = domains.Article
    paginate_by = 6
    template_name = 'site/articles/articles_list.html'

    def get_queryset(self):
        query = domains.Article.objects.filter(is_delete=False, publish_date__lte=datetime.datetime.now(), is_active=True)
        return query


# endregion

# region article short link

def article_short_link(request: HttpRequest, article_id):
    article = domains.Article.objects.get_by_id(article_id)
    if article is not None and article.is_active and not article.is_delete:
        return redirect(article.get_article_detail_url(), permanent=True)

    raise Http404(_('Information not found'))


# endregion

# region article detail

class ArticleDetailPage(View):
    def get(self, request: HttpRequest, article_id, article_title):
        article: domains.Article = domains.Article.objects.get_article_for_show(article_id)
        if article is None:
            raise Http404(_('Information not found'))

        article.visit_count += 1
        article.save()

        comments = domains.ArticleComment.objects.get_article_comments_for_show(article_id)

        context = {
            'article': article,
            'comments': comments,
            'comments_count': domains.ArticleComment.objects.get_article_total_comments_count(article_id),
            'comment_form': AddArticleCommentForm(),
            'current_domain': request.META['HTTP_HOST']
        }
        return render(request, 'site/articles/article_detail.html', context)


# endregion

# region add comment

class AddArticleCommentPage(View):
    def post(self, request: HttpRequest, article_id):
        add_comment_form = AddArticleCommentForm(request.POST)
        article = domains.Article.objects.get_by_id(article_id)
        if add_comment_form.is_valid():
            if article is not None:
                if article.can_add_comment:
                    parent_comment = domains.ArticleComment.objects.get_by_id(add_comment_form.cleaned_data.get('parent_id'))
                    comment = domains.ArticleComment(
                        article_id=article_id,
                        text=add_comment_form.cleaned_data.get('text'),
                        sender_id=request.user.id,
                        comment_state=domains.ArticleComment.ArticleCommentState.NOT_SEEN,
                        parent=parent_comment
                    )
                    comment.save()
                    messages.add_message(request, messages.SUCCESS, _('Your comment will be displayed after review'))
                else:
                    messages.add_message(request, messages.ERROR, _('Can not add comment for this article'))
            else:
                messages.add_message(request, messages.ERROR, _('Information not found'))
        else:
            messages.add_message(request, messages.ERROR, _('Please enter comment text'))

        return redirect(article.get_article_detail_url())

# endregion

apps/site/views/components.py
from django.db.models import Count
from django.http import HttpRequest
from django.shortcuts import render
from apps.admin_panel import models as domains


# region layout

def site_header(request: HttpRequest):
    site_setting: domains.SiteSetting = domains.SiteSetting.objects.first()
    links = domains.DynamicLink.objects.get_active_links_by_position(domains.DynamicLink.LinkPosition.SITE_HEADER)
    context = {
        'links': links,
        'site_setting': site_setting
    }
    return render(request, 'site/components/site_header.html', context)


def site_footer(request: HttpRequest):
    site_setting: domains.SiteSetting = domains.SiteSetting.objects.first()
    links = domains.DynamicLink.objects.get_active_links_by_position(domains.DynamicLink.LinkPosition.SITE_FOOTER)
    context = {
        'links': links,
        'settings': site_setting
    }
    return render(request, 'site/components/site_footer.html', context)


# endregion

# region auth

def auth_description(request: HttpRequest):
    return render(request, 'site/components/auth_description.html')


# endregion

# region articles

def article_categories(request: HttpRequest):
    categories = domains.ArticleCategory.objects.annotate(Count('article')).filter(is_delete=False)
    return render(request, 'site/components/article_categories.html', {
        'categories': categories
    })


def article_most_visited(request: HttpRequest):
    return render(request, 'site/components/article_most_visit.html', {
        'articles': domains.Article.objects.order_by('-visit_count')[:10]
    })

# endregion

apps/site/templates/site/home/about_us.html
{% extends 'shared/layout.html' %}
{% load i18n %}

{% block title %}
    {% trans 'About us' %}
{% endblock %}

{% block content %}
    <section class="page-title">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">

                    <div class="breadcrumbs-wrap">
                        <h1 class="breadcrumb-title">{% trans 'About us' %}</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'home_page' %}">{% trans 'Home' %}</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{% trans 'About us' %}</li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <section class="bg-light">

        <div class="container">

            <!-- row Start -->
            <div class="row">

                <div class="col-lg-8 col-md-7">
                    <div class="prc_wrap">

                        <div class="prc_wrap_header">
                            <h4 class="property_block_title">{% trans 'Abouts us' %}</h4>
                        </div>
                        <div class="p-3">
                            {{ site_setting.about_us_text|safe }}
                        </div>
                    </div>

                </div>

                <div class="col-lg-4 col-md-5">

                    <div class="prc_wrap">

                        <div class="prc_wrap_header">
                            <h4 class="property_block_title">{% trans 'Contact ways' %}</h4>
                        </div>

                        <div class="prc_wrap-body">
                            <div class="contact-info">

                                {% if site_setting.address %}
                                    <div class="cn-info-detail">
                                        <div class="cn-info-icon">
                                            <i class="ti-home"></i>
                                        </div>
                                        <div class="cn-info-content">
                                            <h4 class="cn-info-title">{% trans 'Address' %}</h4>
                                            {{ site_setting.address|safe }}
                                        </div>
                                    </div>
                                {% endif %}

                                {% if site_setting.support_email %}
                                    <div class="cn-info-detail">
                                        <div class="cn-info-icon">
                                            <i class="ti-email"></i>
                                        </div>
                                        <div class="cn-info-content">
                                            <h4 class="cn-info-title">{% trans 'Support email' %}</h4>
                                            {{ site_setting.support_email }}
                                        </div>
                                    </div>
                                {% endif %}

                                {% if site_setting.tell %}
                                    <div class="cn-info-detail">
                                        <div class="cn-info-icon">
                                            <i class="ti-mobile"></i>
                                        </div>
                                        <div class="cn-info-content">
                                            <h4 class="cn-info-title">{% trans 'Tell' %}</h4>
                                            {{ site_setting.tell }}
                                        </div>
                                    </div>
                                {% endif %}

                            </div>
                        </div>
                    </div>

                </div>

            </div>
            <!-- /row -->

        </div>

    </section>
{% endblock %}

apps/site/templates/site/home/index.html
{% extends 'shared/layout.html' %}
{% load i18n thumbnail currency_filter time_filter %}

{% block title %}
    {% trans 'Home page' %}
{% endblock %}

{% block content %}
    <!-- ============================ Hero Banner  Start================================== -->
    <div class="image-cover half_banner" style="background:#0b2248 url(/static/site/rtl/img/banner-1.jpg) no-repeat;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="banner-search-2">
                        <h1 class="cl_2 mb-0">Learn on your<br>schedule</h1>
                        <p>Study any topic, anytime. Choose from thousands of expert-led courses now.</p>
                        <form action="{% url 'courses_list_page' %}" method="get">
                            <div class="input-group mt-3">
                                <input type="text" name="title" class="form-control"
                                       placeholder="What do you want to learn?">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="button">
                                        <img src="/static/site/rtl/img/color-search.svg" class="search-icon" alt="">
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================ Hero Banner End ================================== -->

    <!-- ========================== Featured Category Section =============================== -->
    <section class="bg-light">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <div class="sec-heading center">
                        <p>Popular Category</p>
                        <h2><span class="theme-cl">Hot &amp; Popular</span> Category For Learn</h2>
                    </div>
                </div>
            </div>

            <div class="row">
                {% for category in categories %}
                    <div class="col-lg-4 col-md-4 col-sm-6">
                        <div class="edu_cat_2 cat-{{ forloop.counter }}">
                            <div class="edu_cat_icons">
                                <a class="pic-main" href="#">
                                    {% thumbnail category.image "64x64" crop="center" as im %}
                                        <img src="{{ im.url }}" width="{{ im.width }}"
                                             height="{{ im.height }}" class="img-fluid"
                                             alt="{{ article.title }}">
                                    {% endthumbnail %}
                                </a>
                            </div>
                            <div class="edu_cat_data">
                                <h4 class="title"><a href="#">{{ category.title }}</a></h4>
                                <ul class="meta">
                                    <li class="video">
                                        <i class="ti-video-clapper"></i>
                                        {{ category.course_set.count }} {% trans 'Course' %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>

        </div>
    </section>
    <!-- ========================== Featured Category Section =============================== -->

    <!-- ============================ Featured Courses Start ================================== -->
    <section class="gray min-sec">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <div class="sec-heading center">
                        <p>Hot &amp; Trending</p>
                        <h2><span class="theme-cl">Recent</span> Courses by professional Instructor</h2>
                    </div>
                </div>
            </div>

            <div class="row">
                {% for course in courses %}
                    <div class="col-md-4 col-sm-12">
                        <div class="education_block_grid style_2">
                            <div class="education_block_thumb n-shadow">
                                <a href="{{ course.get_detail_url }}">
                                    <img src="{{ course.image.url }}"
                                         class="img-fluid"
                                         alt="{{ course.title }}"></a>
                            </div>
                            <div class="education_block_body">
                                <h4 class="bl-title">
                                    <a href="{{ course.get_detail_url }}">{{ course.title }}</a></h4>
                            </div>

                            <div class="cources_info">
                                <div class="cources_info_first">
                                    <ul>
                                        <li>
                                            <strong>{{ course.visit_count }} {% trans 'Visit' %}</strong>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cources_info_last">
                                    <h3>{{ course.get_course_price_display }}</h3>
                                </div>
                            </div>

                            <div class="education_block_footer">
                                <div class="education_block_author">
                                    <div class="path-img">
                                        <a href="instructor-detail.html">
                                            <img src="{{ course.main_master.user.get_user_avatar }}"
                                                 class="img-fluid"
                                                 alt=""></a>
                                    </div>
                                    <h5>
                                        <a href="instructor-detail.html">{{ course.main_master.user }}</a>
                                    </h5>
                                </div>
                                <span class="education_block_time">
                                            <i class="ti-alarm-clock ml-1"></i>
                                    {% if course.total_section_duration %}
                                        {{ course.total_section_duration|convert_minutes_to_time }}
                                    {% else %}
                                        00:00
                                    {% endif %}
                                        </span>
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- ============================ Featured Courses End ================================== -->

    <!-- ========================== Articles Section =============================== -->
    <section class="bg-light min-sec">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <div class="sec-heading center">
                        <p>Our Story</p>
                        <h2><span class="theme-cl">Recent</span> Articles to You</h2>
                    </div>
                </div>
            </div>

            <div class="row">
                {% for article in articles %}
                    <div class="col-lg-4 col-md-4 col-sm-12">
                        <div class="articles_grid_style">
                            <div class="articles_grid_thumb">
                                <a href="{{ article.get_article_detail_url }}">
                                    {% thumbnail article.image "626x417" crop="center" as im %}
                                        <img src="{{ im.url }}" width="{{ im.width }}"
                                             height="{{ im.height }}" class="img-fluid"
                                             alt="{{ article.title }}">
                                    {% endthumbnail %}

                                </a>
                            </div>

                            <div class="articles_grid_caption">
                                <h4>{{ article.title }}</h4>
                                <div class="articles_grid_author">
                                    <div class="articles_grid_author_img">
                                        <img src="{{ article.author.get_user_avatar }}"
                                             class="img-fluid" alt=""></div>
                                    <h4>{{ article.author.get_full_name }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}